// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreBootcampT27APIERSQL_EX3;

namespace NetCoreBootcampT27APIERSQL_EX3.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210622185201_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("NetCoreBootcampT27APIERSQL_EX3.Models.Cajero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NomApels");

                    b.HasKey("Id");

                    b.ToTable("Cajeros");
                });

            modelBuilder.Entity("NetCoreBootcampT27APIERSQL_EX3.Models.MaquinaRegistradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MaquinasRegistradoras");
                });

            modelBuilder.Entity("NetCoreBootcampT27APIERSQL_EX3.Models.Producto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("NetCoreBootcampT27APIERSQL_EX3.Models.Venta", b =>
                {
                    b.Property<int>("CajeroId")
                        .HasColumnType("int")
                        .HasColumnName("Cajero");

                    b.Property<int>("MaquinaRegistradoraId")
                        .HasColumnType("int")
                        .HasColumnName("Maquina");

                    b.Property<string>("ProductoId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Producto");

                    b.HasKey("CajeroId", "MaquinaRegistradoraId", "ProductoId");

                    b.HasIndex("MaquinaRegistradoraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("NetCoreBootcampT27APIERSQL_EX3.Models.Venta", b =>
                {
                    b.HasOne("NetCoreBootcampT27APIERSQL_EX3.Models.Cajero", "Cajero")
                        .WithMany()
                        .HasForeignKey("CajeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCoreBootcampT27APIERSQL_EX3.Models.MaquinaRegistradora", "MaquinaRegistradora")
                        .WithMany()
                        .HasForeignKey("MaquinaRegistradoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCoreBootcampT27APIERSQL_EX3.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cajero");

                    b.Navigation("MaquinaRegistradora");

                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
