// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreBootcampT27APIERSQL;

namespace NetCoreBootcampT27APIERSQL_EX1.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210622181614_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("NetCoreBootcampT27APIERSQL.Models.Pieza", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Codigo");

                    b.ToTable("Piezas");
                });

            modelBuilder.Entity("NetCoreBootcampT27APIERSQL.Models.Proveedor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("NetCoreBootcampT27APIERSQL.Models.Suministra", b =>
                {
                    b.Property<int>("PiezaId")
                        .HasColumnType("int")
                        .HasColumnName("CodigoPieza");

                    b.Property<string>("ProveedorId")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("IdProveedor");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("PiezaId", "ProveedorId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Suministras");
                });

            modelBuilder.Entity("NetCoreBootcampT27APIERSQL.Models.Suministra", b =>
                {
                    b.HasOne("NetCoreBootcampT27APIERSQL.Models.Pieza", "Pieza")
                        .WithMany()
                        .HasForeignKey("PiezaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCoreBootcampT27APIERSQL.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pieza");

                    b.Navigation("Proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
